### ISSUE TITLE
Tests and Travis

### ISSUE THREAD

**Issue by asmodehn** [Kentzo/git-archive-all#28]
It would be very useful to have a test suite.
We could make sure we don't regress when proposing a pull request.
At the moment only pep8 check is done...

**Comment by Kentzo** [comment]
I agree, would be nice to have. Does it allow to work with git there though?

**Comment by asmodehn** [comment]
Sure. You can do like this :https://github.com/vcstools/vcstools/blob/master/.travis.yml
The tests there play around with git ( and test git_archive_all.py among other things )

**Comment by Kentzo** [comment]
Tests to add:

- [ ] Test with a non-git directory
- [ ] Test with a plain git repo
- [ ] Test with a git repo with a nested submodule
- [ ] Test with a git repo with multiple nested submodules
- [ ] Test with a git repo with a tree of submodules
- [ ] Test with .gitattributes for each of the cases above
- [ ] Test with .gitattributes but with `--no-exclude` for each of the cases above
- [ ] Test for relative and absolute extra files
- [ ] Test for prefix
