### ISSUE TITLE
Windows: pwd: command not found

### ISSUE THREAD

**Issue by NiklasRosenstein** [Kentzo/git-archive-all#33]
I am not sure how much related to git-archive-all this actually is, but this is the first time I encounter this error message.

```
λ git archive-all c4ddev-v1.1.zip
C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 336: 'pwd: command not found
Stopping at 'lib/py-localimport'; script returned non-zero status.
Command 'git submodule --quiet foreach 'pwd -P'' returned non-zero exit status 1
```

I've tried running the same command from `bash` to no avail, although running `pwd` from the Git `bash` actually works fine. Any idea how to fix this? Thanks!

**Comment by Kentzo** [comment]
@NiklasRosenstein Hmm, something wrong with PATH when git executes subcommand?

**Comment by scw** [comment]
This is resolved by updating to the latest code, the fix that went in in PR #29 makes this work fine. In installed with `python setup.py build install` and the code worked fine on Windows. Could you release a 1.14 for distribution on PyPI for the recent changes? Thanks!

**Comment by Kentzo** [comment]
@scw sure thing.

**Comment by Kentzo** [comment]
@scw New version (1.15) us now available on pypi.

**Comment by scw** [comment]
Thanks @Kentzo! New release works great on my end.
