### ISSUE TITLE
Paths won't be ignored correctly

### ISSUE THREAD

**Issue by alehaa** [Kentzo/git-archive-all#42]
Correct me if I'm wrong, but afaik one may exclude a specific file / path by using the path in the repository with a leading slash, i.e. `tests` would ignore all files and directories named `tests`, while `/tests` would just ignore `/tests` but not `/fancy/tests`.

However, paths will be checked without leading slash, so the pattern `/tests` will never match.

**Comment by Kentzo** [comment]
Should simple to check with vanilla `git archive`.

**Comment by Kentzo** [comment]
PR #45 should make git-archive-all to follow git exclusion rules.
