### ISSUE TITLE
Zip archive path

### ISSUE THREAD

**Issue by envisiagroup** [Kentzo/git-archive-all#43]
The archive created automatically includes a path based on the given archive name, ie: 
`git-archive-all blablabla.zip`
```
unzip -l blablabla.zip
blablabla/me.txt
blablabla/you.txt
```
Please include a way to use a given path similar to "git -C /path/of/folder/to/run/git/".  When you run 'git archive', it doesn't include a path in the archive file.

**Comment by Kentzo** [comment]
@envisiagroup Have you tried the `--prefix` option?
