### ISSUE TITLE
Doesn't support unsetting export-ignore

### ISSUE THREAD

**Issue by legoktm** [Kentzo/git-archive-all#44]
Hi, we're looking to use this to replace our homegrown release script for MediaWiki, and it nearly has all the functionality we need. The one thing I noticed is that it doesn't appear to support unsetting the `export-ignore` attribute (as documented in <https://www.git-scm.com/docs/gitattributes>).

We want to ignore all dot files except for `.htaccess`, so I have the following in our .gitattributes:
```
.* export-ignore
*.htaccess -export-ignore
```

A standard `git archive ...` will include the .htaccess files, but it doesn't include the submodules that we want.

Would it be possible to have git-archive-all support unsetting the export-ignore property?

I wonder whether it would make more sense in the long term to rely on git's attribute parsing, e.g.:
```
$ git check-attr -a -- .eslintrc.json 
.eslintrc.json: export-ignore: set
$ git check-attr -a -- cache/.htaccess 
cache/.htaccess: export-ignore: unset
```

**Comment by Kentzo** [comment]
Didn't know of this feature.

Do you happen to recall when it was added to Git?

**Comment by legoktm** [comment]
It was introduced in https://github.com/git/git/commit/e4aee10a2eaf0937d86d046f85ee569a75cae9ac (11 years ago).

**Comment by Kentzo** [comment]
Perhaps the simplest fix is to [check](https://github.com/Kentzo/git-archive-all/blob/16a79f79f67c4df37a35b993f800600a4d1673e6/git_archive_all.py#L191-L192) for `"-export-ignore"` before `"export-ignore"`.

**Comment by legoktm** [comment]
I tried to just implement checking for -export-ignore but it ended up being more complicated than I expected, so I went ahead with the `check-attr` implementation and then I realized I could delete a ton of code.

**Comment by Kentzo** [comment]
I like it 👍
