### ISSUE TITLE
ZIP Compression level

### ISSUE THREAD

**Issue by mazegen** [Kentzo/git-archive-all#54]
Can you please support this feature of `git archive`?

https://git-scm.com/docs/git-archive#_backend_extra_options

And thank you for this tool, it's very useful.

**Comment by Kentzo** [comment]
Good request. Take a look at the issue-54 branch.

**Comment by mazegen** [comment]
Well, I'm not a Python programmer but as far as I can tell, the modification looks right :)

**Comment by Kentzo** [comment]
Could you try it out for you tasks?

**Comment by mazegen** [comment]
Sorry for late reply. Many thanks for implementing this, it works for me. We have ultimate git export tool now.
