### ISSUE TITLE
Segment fault when output as tar.bz2

### ISSUE THREAD

**Issue by wuzhouhui** [Kentzo/git-archive-all#59]
Reproduce steps: `./git_archive_all.py a.tar.bz2`
OS: Ubuntu 18.04
Python: 2.7.15rc1

**Comment by Kentzo** [comment]
Hi @wuzhouhui,

What version of git-archive-all are you running? What is the version of git?

If you have Python 3.3+, please try to reproduce the problem by running it like this:

> python3 -q -X faulthandler ./git_archive_all.py a.tar.bz2

**Comment by wuzhouhui** [comment]
> Hi @wuzhouhui,
> 
> What version of git-archive-all are you running? What is the version of git?

version of git-archive-all is 1.19.0, version of git is 2.17.1
> 
> If you have Python 3.3+, please try to reproduce the problem by running it like this:
> 
> > python3 -q -X faulthandler ./git_archive_all.py a.tar.bz2

I'm using Python-3.6.6 to run `python3 -q -X faulthandler ./git_archive_all.py a.tar.bz2`, and segfault doesn't appered. a.tar.bz2 generated successfully, thanks.

**Comment by Kentzo** [comment]
@wuzhouhui Hmm, that's not expected :) `-q -X faulthandler` is supposed to give more details when segfault happens.

Is there anything unusual about the repo? Does it have submodules or

**Comment by wuzhouhui** [comment]
Maybe my Python-2.7.15rc1 is broken.

**Comment by Kentzo** [comment]
Could you try [1.18.3](https://github.com/Kentzo/git-archive-all/releases/tag/1.18.3)?

**Comment by wuzhouhui** [comment]
> Could you try [1.18.3](https://github.com/Kentzo/git-archive-all/releases/tag/1.18.3)?

The segfault doesn't happens in 1.18.3:
```
$ git checkout 1.18.3
$ ./git_archive_all.py a.tar.bz2
$ git status
HEAD detached at 1.18.3
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	a.tar.bz2

nothing added to commit but untracked files present (use "git add" to track)
```
The version of python that runs script is 2.7.15rc1

**Comment by Kentzo** [comment]
With 1.19.0 and python 2.7, could you try `python ./git_archive_all.py --dry-run -vv a.tar.bz2`?

**Comment by wuzhouhui** [comment]
> With 1.19.0 and python 2.7, could you try `python ./git_archive_all.py --dry-run -vv a.tar.bz2`?

```
$ git checkout 1.19.0
$ python2.7 ./git_archive_all.py --dry-run -vv a.tar.bz2
Output format is not explicitly set, determined format is bz2.
/home/wzh/Downloads/git-archive-all/.gitignore => a/.gitignore
/home/wzh/Downloads/git-archive-all/.travis.yml => a/.travis.yml
/home/wzh/Downloads/git-archive-all/CHANGES.rst => a/CHANGES.rst
/home/wzh/Downloads/git-archive-all/LICENSE.txt => a/LICENSE.txt
/home/wzh/Downloads/git-archive-all/MANIFEST.in => a/MANIFEST.in
/home/wzh/Downloads/git-archive-all/Makefile => a/Makefile
/home/wzh/Downloads/git-archive-all/README.rst => a/README.rst
/home/wzh/Downloads/git-archive-all/git_archive_all.py => a/git_archive_all.py
/home/wzh/Downloads/git-archive-all/requirements.txt => a/requirements.txt
/home/wzh/Downloads/git-archive-all/setup.cfg => a/setup.cfg
/home/wzh/Downloads/git-archive-all/setup.py => a/setup.py
/home/wzh/Downloads/git-archive-all/test_git_archive_all.py => a/test_git_archive_all.py
$ python2.7 ./git_archive_all.py  -vv a.tar.bz2
Output format is not explicitly set, determined format is bz2.
Segmentation fault (core dumped)
```

**Comment by Kentzo** [comment]
Interesting. So the exception happen when you try to archive it.

Could you try other formats, namely:

```
python2.7 ./git_archive_all.py  -vv a.tar.gz
python2.7 ./git_archive_all.py  -vv a.tar.xz
python2.7 ./git_archive_all.py  -vv a.tar
python2.7 ./git_archive_all.py  -vv a.zip
```

?

**Comment by Kentzo** [comment]
In other words it works for all formats except xz (not supported by Python 2.7) and bz2?

**Comment by wuzhouhui** [comment]
> Could you test git_archive_all.py from the master branch?

After pull latest changes from master, `./git_archive_all.py a.tar.bz2` works well:
```
$ git log -1 --oneline 
c89a03d (HEAD -> master, origin/master, origin/HEAD) Do not pass compresslevel unless set by user.
$ ./git_archive_all.py a.tar.bz2
$ git status
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	a.tar.bz2

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by Kentzo** [comment]
Ok, that concludes the problem then. Thank you for the testing!
