### ISSUE TITLE
The command that contains git check-attr looks incompatible with Windows

### ISSUE THREAD

**Issue by mazegen** [Kentzo/git-archive-all#62]
On my Windows 10, the following works right:

    git checkout tags/1.16.4
    git_archive_all.py x.zip

But the following throws error:

    git checkout tags/1.19.1
    git_archive_all.py x.zip

> 'GIT_FLUSH' is not recognized as an internal or external command,
> operable program or batch file.
> check-attr exited prematurely

It seems like the problem is here:

    cmd = 'GIT_FLUSH=1 git check-attr --stdin -z {0}'.format(' '.join(attrs))

I'm not sure about the syntax that is used here but if I change it to the following (just guessing), it seems to work right:

    cmd = 'set GIT_FLUSH=1 && git check-attr --stdin -z {0}'.format(' '.join(attrs))

**Comment by Kentzo** [comment]
Didn't know that the script even works on Windows :)

**Comment by mazegen** [comment]
Yeah, it's cmd.exe. I didn't know the script has unix shell dependency now. Can it be fixed?

**Comment by Kentzo** [comment]
Please try the issue-62 branch.

**Comment by mazegen** [comment]
It works, at least with git-archive-all itself, thanks :)
