### ISSUE TITLE
Archive a specific tag

### ISSUE THREAD

**Issue by Gustry** [Kentzo/git-archive-all#72]
With `git archive`, it's possible to archive a specific tag. It seems not possible with `git-archive-all`.

Thanks for this package, this should be in git core! ;-)

**Comment by Kentzo** [comment]
It is but not directly. The CLI does not accept the `<tree-ish>` argument, but you can always do `git checkout` before

**Comment by Kentzo** [comment]
Closing the issue, as I currently cannot think of a non-destructive implementation.

**Comment by Gustry** [comment]
Yes, it's alright. It's indeed tricky. Thanks
