### ISSUE TITLE
Ignore uncommitted changes in submodules

### ISSUE THREAD

**Issue by ernstwi** [Kentzo/git-archive-all#89]
Steps to reproduce:

1. Make a change in a submodule and do not commit it
2. `git-archive-all example.tar`

Result: The uncommitted change in the submodule is present in the result.

Expected result: The submodule state should be equal to the commit hash which is saved in parent repo and not contain the uncommitted change.

**Comment by Kentzo** [comment]
The algorithm does not modify the file tree, it reads the files as is relying on git to tell which files should be included.

Unless newer versions of git have a command to read arbitrary version of a file without changing the worktree I don't think it can happen. However, consider a case where the change is a different commit of a submodule of a submodule (2 levels deep). How would you handle this cleanly?

As a workaround, I can probably add an option to stash / unstash every encountered repo but won't address the case above.

**Comment by ernstwi** [comment]
> read arbitrary version of a file without changing the worktree

There is `git show`: `git show xyz:index.js` outputs file `index.js` at commit `xyz`.

I haven't looked at the code yet so have no idea how difficult it would be to implement, sorry, just wanted to put the idea out there. The reason this was unexpected behaviour to me is that it behaves differently than `git archive` which takes a specific hash/ref and archives the content at that commit.

> However, consider a case where the change is a different commit of a submodule of a submodule (2 levels deep). How would you handle this cleanly?

In this case I think it would work recursively for each submodule encountered, regardless of level:

1. Look at what hash is registered in the parent.
2. Output the state of the submodule at this hash (e.g. using `git show`).

An alternative to `git show` on each file might also be to leverage `git archive` on submodules, no?
