### ISSUE TITLE
Tests failing with "ResourceWarning: unclosed file" when new test dependencies are used

### ISSUE THREAD

**Issue by fgaz** [Kentzo/git-archive-all#90]
I'm packaging git-archive-all for NixOS, and I'm trying to update the test dependencies because the specified version are very old, but on almost all tests I'm getting `ResourceWarning: unclosed file <_io.BufferedReader name='[...]/repo.tar'>`.

All distributions that package git-archive-all currently disable tests because of this.

Removing `filterwarnings = error` also fixes the issue (we do this in the NixOS package), but then the warnings are ignored.

**Comment by Kentzo** [comment]
Should be address in master.
